version: '3.1'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: rufet
      POSTGRES_PASSWORD: mezemov15032000
      POSTGRES_DB: dynamicquery
    ports:
      - "5432-5432"